/**
 * AIProductsDataSource — AI产品分析 数据加载层
 *
 * 三层架构（与 BlogDataSource 一致）：
 *   - src/lib/ai-products-meta.json     → 全语言元数据（用于 slug 查找 + build-routes）
 *   - src/lib/ai-products-meta-{locale}.json × 5 → per-locale 元数据（按需加载，~10KB/语言）
 *   - src/lib/ai-products-data/{slug}.json × N → per-slug 完整内容（详情页懒加载，~50-80KB/slug）
 *   - src/lib/ai-products-data.json     → 全量内容（仅脚本使用，不进 bundle）
 */
import type { AIProduct } from "@/config/site";
import { normalizeLang, type SupportedLocale } from "@/lib/locale";
import metaDataAll from "./ai-products-meta.json";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type AIProductMeta = Omit<AIProduct, "content">;
export type AIProductPost = AIProduct;

// JSON module manifests typed via generic helpers to keep imports clean.
type MetaManifest = { products: AIProductMeta[] };
type LocaleKey = "zh-Hans" | "zh-Hant" | "en" | "ja" | "vi";

// ---------------------------------------------------------------------------
// Locale → module map (static, tree-shakeable)
// ---------------------------------------------------------------------------

const localeMetaModules: Record<LocaleKey, () => Promise<{ default: MetaManifest }>> = {
  "zh-Hans": () => import("./ai-products-meta-zh-Hans.json"),
  "zh-Hant": () => import("./ai-products-meta-zh-Hant.json"),
  en: () => import("./ai-products-meta-en.json"),
  ja: () => import("./ai-products-meta-ja.json"),
  vi: () => import("./ai-products-meta-vi.json"),
};

// Per-slug content loaders, generated by Vite as separate chunks.
// Adding a new slug requires no code change — Vite picks up the glob.
const slugLoaders = import.meta.glob<{ default: AIProductPost }>(
  "./ai-products-data/*.json"
);

function loaderFor(slug: string) {
  return slugLoaders[`./ai-products-data/${slug}.json`];
}

// ---------------------------------------------------------------------------
// Helper: localise text field
// ---------------------------------------------------------------------------

function resolveText(
  value: string | Record<string, string> | undefined,
  lang: SupportedLocale
): string {
  if (!value) return "";
  if (typeof value === "string") return value;
  return (
    value[lang] ||
    value["zh-Hans"] ||
    value.en ||
    Object.values(value).find(Boolean) ||
    ""
  );
}

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

export class AIProductsDataSource {
  private static _instance: AIProductsDataSource;
  private _posts: AIProductMeta[];

  private constructor() {
    this._posts = (metaDataAll as MetaManifest).products ?? [];
  }

  public static getInstance(): AIProductsDataSource {
    if (!AIProductsDataSource._instance) {
      AIProductsDataSource._instance = new AIProductsDataSource();
    }
    return AIProductsDataSource._instance;
  }

  /** All products (all languages, metadata only). Sync. */
  getPosts(): AIProductMeta[] {
    return this._posts;
  }

  /** Per-locale products (metadata only). Async — uses code-split chunks. */
  async getPostsLocalized(locale: SupportedLocale): Promise<AIProductMeta[]> {
    const keyedLocale = normalizeLang(locale) as LocaleKey;
    const loader = localeMetaModules[keyedLocale] ?? localeMetaModules["zh-Hans"];
    const mod = await loader();
    return (mod.default.products as AIProductMeta[]) ?? [];
  }

  /** Sync: look up by slug from the all-language index (metadata only). */
  getPostBySlug(slug: string): AIProductMeta | undefined {
    return this._posts.find((p) => p.slug === slug);
  }

  /**
   * Async: load full content (Markdown + product info + pricing + metrics + sources).
   * Falls back to metadata-only when per-slug chunk is missing.
   */
  async getPostWithContent(slug: string): Promise<AIProductPost | undefined> {
    const loader = loaderFor(slug);
    if (loader) {
      try {
        const mod = await loader();
        return mod.default;
      } catch {
        // Fall through to metadata-only fallback.
      }
    }
    return this.getPostBySlug(slug);
  }

  /**
   * Resolve a meta/post to the target locale — flattens Record<locale, string>
   * fields into plain strings. Used by React components.
   */
  resolve(post: AIProductMeta | AIProductPost, locale: SupportedLocale) {
    const normalized = normalizeLang(locale) as SupportedLocale;
    return {
      ...post,
      title: resolveText(post.title, normalized),
      description: resolveText(post.description, normalized),
      content: "content" in post ? resolveText(post.content, normalized) : undefined,
    };
  }
}

export const aiProductsDataSource = AIProductsDataSource.getInstance();
