/**
 * BlogDataSource — three-tier strategy:
 *
 *   blog-meta-{locale}.json  (~80 KB per locale) → metadata only (title/description pre-localized)
 *                                                      Loaded eagerly on BlogIndex; zero localizeText() overhead
 *
 *   blog-meta.json           (430 KB) → all languages metadata (for build-routes + BlogPost slug lookup)
 *
 *   blog-data/{slug}.json    (~90 KB per slug) → full content for ONE post (all locales).
 *                                                  Loaded lazily on BlogPost detail page.
 *                                                  Built by scripts/build-blog.js.
 *
 *   blog-data.json           (9.9 MB) → legacy monolith, kept for sitemap/scripts that need
 *                                          all posts at once. Not imported by client code.
 *
 * Per-slug files reduce the detail page's network + parse cost from 9.9 MB → ~90 KB
 * (a 100× improvement) and turn prerender of /blog/:slug from "load 13 MB" to "load 90 KB".
 */
import type { BlogPost } from "@/config/site";
import { normalizeLang, type SupportedLocale } from "@/lib/locale";
import metaDataAll from "./blog-meta.json";

// Re-export types for consumers
export type BlogMeta = Omit<BlogPost, "content">;

// Locale → module map (static, tree-shakeable)
const localeMetaModules = {
  "zh-Hans": () => import("./blog-meta-zh-Hans.json"),
  "zh-Hant": () => import("./blog-meta-zh-Hant.json"),
  en: () => import("./blog-meta-en.json"),
  ja: () => import("./blog-meta-ja.json"),
  vi: () => import("./blog-meta-vi.json"),
} as const;

// Per-slug content loaders, generated by Vite as separate chunks.
// `eager: false` produces lazy chunks; `import: "default"` unwraps the default export.
// The glob pattern covers the whole directory so adding a new slug requires no code change.
const slugLoaders = import.meta.glob<{ default: BlogPost }>("./blog-data/*.json");

function loaderFor(slug: string): (() => Promise<{ default: BlogPost }>) | undefined {
  return slugLoaders[`./blog-data/${slug}.json`];
}

export class BlogDataSource {
  private static _instance: BlogDataSource;
  private _posts: BlogMeta[];

  private constructor() {
    // Default: load all-languages meta for slug lookups (build-routes, etc.)
    this._posts = (metaDataAll.posts as BlogMeta[]) ?? [];
  }

  public static getInstance(): BlogDataSource {
    if (!BlogDataSource._instance) {
      BlogDataSource._instance = new BlogDataSource();
    }
    return BlogDataSource._instance;
  }

  /** Returns all posts (all languages, metadata only). Safe to call eagerly. */
  getPosts(): BlogMeta[] {
    return this._posts;
  }

  /**
   * Returns posts localized for the given locale.
   * Uses per-locale blog-meta-{locale}.json for efficient loading (80% smaller).
   * Returns all posts with title/description already in the target locale.
   */
  async getPostsLocalized(locale: SupportedLocale): Promise<BlogMeta[]> {
    const loader = localeMetaModules[locale] ?? localeMetaModules["zh-Hans"];
    const module = await loader();
    return (module.default.posts as BlogMeta[]) ?? [];
  }

  /**
   * Returns a post by slug (all languages, metadata only).
   * NOTE: this returns metadata only. The `content` field is always undefined.
   * For full content use getPostWithContent(slug) instead.
   */
  getPostBySlug(slug: string): BlogMeta | undefined {
    return this._posts.find((p) => p.slug === slug);
  }

  /**
   * Loads the per-slug content file (~90 KB) and returns the full BlogPost.
   * Falls back to scanning blog-meta if the per-slug file is missing
   * (e.g., a post was added to meta but not yet built).
   */
  async getPostWithContent(slug: string): Promise<BlogPost | undefined> {
    const loader = loaderFor(slug);
    if (loader) {
      try {
        const mod = await loader();
        return mod.default;
      } catch {
        // Per-slug file exists at build time but failed to load at runtime;
        // fall through to metadata-only fallback below.
      }
    }
    // Fallback: metadata-only (content will be undefined).
    return this.getPostBySlug(slug);
  }
}

export const blogDataSource = BlogDataSource.getInstance();
